# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Slow-test
on:
  schedule:
    - cron: '0 7 * * *'
jobs:
  slow-test:
    name: slow-test
    runs-on: macOS-latest
    env:
      QISKIT_IBM_API_TOKEN: ${{ secrets.QISKIT_IBM_API_TOKEN }}
      QISKIT_IBM_API_URL: ${{ secrets.QISKIT_IBM_API_URL }}
      QISKIT_IBM_HGP: ${{ secrets.QISKIT_IBM_HGP }}
      QISKIT_IBM_CLOUD_TOKEN: ${{ secrets.QISKIT_IBM_CLOUD_TOKEN }}
      QISKIT_IBM_CLOUD_URL: ${{ secrets.QISKIT_IBM_CLOUD_URL }}
      QISKIT_IBM_CLOUD_CRN: ${{ secrets.QISKIT_IBM_CLOUD_CRN }}
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_TESTS: run_slow
      QISKIT_IN_PARALLEL: True
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints.txt -e .
          pip install -U -c constraints.txt -r requirements-dev.txt
      - name: Run Tests
        run: make test
